# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: 'Lock Threads'

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: '365'
          issue-lock-reason: >
            This thread has been automatically locked since there has not been
            any recent activity after it was closed. Please open a new issue for
            related bugs.
          pr-inactive-days: '365'
          pr-lock-reason: >
            This thread has been automatically locked since there has not been
            any recent activity after it was closed. Please open a new issue for
            related bugs.
          log-output: false
